[package]
name = "jiyunet-core"
version = "0.1.0"
authors = ["treyzania <treyzania@gmail.com>"]

[dependencies]
byteorder = "1"
rust-crypto = "^0.2"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
