[package]
name = "jiyunet-validation"
version = "0.1.0"
authors = ["treyzania <treyzania@gmail.com>"]

[dependencies]
jiyunet-core = { path = "../core" }
jiyunet-dag = { path = "../dag" }
jiyunet-db = { path = "../db" }
