[package]
name = "libjiyunet-validation"
version = "0.1.0"
authors = ["treyzania <treyzania@gmail.com>"]

[dependencies]
libjiyunet-core = { path = "../core" }
libjiyunet-dag = { path = "../dag" }
libjiyunet-db = { path = "../db" }
